name: startsida

services:
    server:
        image: playlogo/startsida
        build: .
        volumes:
            - ./data:/app/data
        ports:
            - "8000:8000"
        network_mode: "host"
