name: startsida

services:
    server:
        image: playlogo/startsida
        restart: "unless-stopped"
        user: "1000"
        build: .
        volumes:
            - ./data:/app/data
            - ./cache:/app/cache
        ports:
            - "8000:8000"
        network_mode: "host"
