name: startsida

services:
    api:
        image: playlogo/startsida
        container_name: startsida
        restart: "unless-stopped"
        user: "1000"
        build: .
        volumes:
            - ./data:/app/data:rw
            - ./cache:/app/cache:rw
        ports:
            - "8000:8000"
        network_mode: "host"

    imgproxy:
        image: ghcr.io/imgproxy/imgproxy:latest
        container_name: imgproxy
        restart: unless-stopped
        ports:
            - "8002:8080"
        environment:
            - IMGPROXY_BASE_URL=https://host.docker.internal:8001/
            - IMGPROXY_ENABLE_WEBP=true
            - IMGPROXY_QUALITY=85
            - IMGPROXY_PREFERRED_FORMATS=webp
            - IMGPROXY_MAX_SRC_RESOLUTION=9999
            - IMGPROXY_IGNORE_SSL_VERIFICATION=true
        extra_hosts:
            - "host.docker.internal:host-gateway"
